/**
 * Centralized error codes for the application
 * Makes it easy to track and handle specific error types
 */

export const ERROR_CODES = {
  // Credits errors (402)
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  CREDITS_CHECK_FAILED: 'CREDITS_CHECK_FAILED',
  
  // OpenAI errors (503)
  OPENAI_ERROR: 'OPENAI_ERROR',
  OPENAI_RATE_LIMIT: 'OPENAI_RATE_LIMIT',
  OPENAI_NO_CREDITS: 'OPENAI_NO_CREDITS',
  OPENAI_QUOTA_EXCEEDED: 'OPENAI_QUOTA_EXCEEDED',
  
  // ElevenLabs errors (503)
  ELEVENLABS_ERROR: 'ELEVENLABS_ERROR',
  ELEVENLABS_QUOTA_EXCEEDED: 'ELEVENLABS_QUOTA_EXCEEDED',
  ELEVENLABS_RATE_LIMIT: 'ELEVENLABS_RATE_LIMIT',

  // Runware errors (503)
  RUNWARE_ERROR: 'RUNWARE_ERROR',
  RUNWARE_INSUFFICIENT_CREDITS: 'RUNWARE_INSUFFICIENT_CREDITS',
  RUNWARE_RATE_LIMIT: 'RUNWARE_RATE_LIMIT',
  
  // YanBrainServer errors
  YANBRAIN_SERVER_ERROR: 'YANBRAIN_SERVER_ERROR',
  
  // Authentication errors (401)
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  
  // Validation errors (400)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_PARAMETERS: 'MISSING_PARAMETERS',
  
  // General errors
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

export default ERROR_CODES;
