import officeParser from 'officeparser';
import { AppError } from '../errors/AppError';

const SUPPORTED_FORMATS = ['pdf', 'docx', 'doc', 'rtf', 'xlsx', 'xls', 'pptx', 'ppt', 'odt', 'odp', 'ods', 'txt', 'md'];
const MAX_TEXT_LENGTH = 500000; // 500KB limit

export async function convertDocumentToText(fileBuffer: Buffer, filename: string): Promise<string> {
    try {
        const ext = filename.toLowerCase().split('.').pop() || '';

        if (!SUPPORTED_FORMATS.includes(ext)) {
            throw AppError.validationError(
                `Unsupported file format: ${filename}. Supported: ${SUPPORTED_FORMATS.join(', ')}`,
                ['filename']
            );
        }

        // Extract text
        const rawText = (ext === 'txt' || ext === 'md')
            ? fileBuffer.toString('utf-8')
            : (await officeParser.parseOffice(fileBuffer, {
                outputErrorToConsole: false,
                newlineDelimiter: '\n',
                ignoreNotes: false,
                putNotesAtLast: false
            })).toText();

        if (!rawText?.trim()) {
            throw AppError.validationError(`No text extracted from: ${filename}`, ['file']);
        }

        // Size check
        if (rawText.length > MAX_TEXT_LENGTH) {
            console.warn(`[DocumentConverter] Large file: ${filename} (${rawText.length} chars)`);
        }

        // Clean text
        const cleanedText = cleanText(rawText);

        if (!cleanedText.length) {
            throw AppError.validationError(`Document contains no useful text: ${filename}`, ['file']);
        }

        console.log(`[DocumentConverter] ${filename}: ${rawText.length} → ${cleanedText.length} chars`);
        return cleanedText;

    } catch (error: any) {
        if (error instanceof AppError) throw error;
        throw AppError.providerError('officeparser', error.message || 'Conversion failed', error);
    }
}

function cleanText(text: string): string {
    // Normalize line breaks
    text = text.replace(/\r\n/g, '\n').replace(/\r/g, '\n');

    // Remove page numbers (full line only)
    text = text.replace(/^Page \d+ of \d+$/gim, '');
    text = text.replace(/^\s*-\s*\d+\s*-\s*$/gm, ''); // Only "- 5 -" style

    // Remove common footers (full line only)
    text = text.replace(/^©.*\d{4}.*$/gim, ''); // Fixed: added 'i'
    text = text.replace(/^Confidential\s*-?\s*Internal Use Only$/gim, '');
    text = text.replace(/^Printed on:.*$/gim, '');
    text = text.replace(/^Generated by:.*$/gim, '');

    // Remove spreadsheet/presentation metadata
    text = text.replace(/^Sheet\d+\s*$/gim, '');
    text = text.replace(/^Slide \d+\s*$/gim, '');

    // Remove box drawing and zero-width characters
    text = text.replace(/[│─┌┐└┘├┤┬┴┼]/g, '');
    text = text.replace(/[\u200B-\u200D\uFEFF]/g, '');

    // Normalize whitespace
    text = text.replace(/[ \t]+/g, ' ');
    text = text.replace(/\n{4,}/g, '\n\n\n');

    // Clean lines
    return text
        .split('\n')
        .map(line => line.trim())
        .filter(line => line.length > 0)
        .join('\n')
        .trim();
}